Pim\Bundle\MagentoConnectorBundle\Entity\MagentoGroupMapping:
    type: entity
    table: pim_magento_group_mapping
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        magentoUrl:
            type: text
            length: 255
            column: magento_url
        magentoGroupId:
            type: integer
            column: magento_group_id
    manyToOne:
        group:
            targetEntity: Pim\Bundle\CatalogBundle\Entity\AttributeGroup
            inversedBy: magentoGroupMappings
            joinColumn:
                name: group_id
                referencedColumnName: id
                onDelete: 'CASCADE'
                unique: true
