Pim\Bundle\MagentoConnectorBundle\Entity\MagentoGroupMapping:
    type: entity
    table: pim_magento_group_mapping
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        magentoUrl:
            type: text
            length: 255
            column: magento_url
        magentoGroupId:
            type: integer
            column: magento_group_id
        pimGroupCode:
            type: string
            column: pim_group_code
        pimFamilyCode:
            type: string
            column: pim_family_code
