connector:
    name: Magento Connector
    jobs:
        magento_product_export:
            title: pim_magento_connector.jobs.product_export.title
            type:  export
            steps:
                # export_simple_products:
                #     title:     pim_magento_connector.jobs.simple_product_export.export.title
                #     services:
                #         reader:    pim_magento_connector.reader.orm.bulk_simple_product
                #         processor: pim_magento_connector.processor.product
                #         writer:    pim_magento_connector.writer.product
                # export_configurable_product:
                #     title:     pim_magento_connector.jobs.configurable_product_export.export.title
                #     services:
                #         reader:    pim_magento_connector.reader.orm.bulk_configurable_product
                #         processor: pim_magento_connector.processor.configurable
                #         writer:    pim_magento_connector.writer.product
                export_product_association:
                    title:     pim_magento_connector.jobs.association_product_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.orm.bulk_product_association
                        processor: pim_magento_connector.processor.product_association
                        writer:    pim_magento_connector.writer.product_association
        magento_category_export:
            title: pim_magento_connector.jobs.category_export.title
            type:  export
            steps:
                export_categories:
                    title:     pim_magento_connector.jobs.category_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.orm.category
                        processor: pim_magento_connector.processor.category
                        writer:    pim_magento_connector.writer.category
                    parameters:
                        batch_size: 1
