connector:
    name: Magento Connector
    jobs:
        magento_product_export:
            title: pim_magento_connector.jobs.product_export.title
            type:  export
            steps:
                export_simple_products:
                    title:     pim_magento_connector.jobs.simple_product_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.orm.bulk_simple_product
                        processor: pim_magento_connector.processor.product
                        writer:    pim_magento_connector.writer.product
                export_configurable_product:
                    title:     pim_magento_connector.jobs.configurable_product_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.orm.bulk_configurable_product
                        processor: pim_magento_connector.processor.configurable
                        writer:    pim_magento_connector.writer.product
                export_product_association:
                    title:     pim_magento_connector.jobs.association_product_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.orm.bulk_product_association
                        processor: pim_magento_connector.processor.product_association
                        writer:    pim_magento_connector.writer.product_association
                prune_simple_products:
                    title: pim_import_export.jobs.simple_product_clean.clean.title
                    class: "%pim_magento_connector.step.prune.class%"
                    services:
                        cleaner: pim_magento_connector.cleaner.product
                prune_configurable_products:
                    title: pim_import_export.jobs.configurable_product_clean.clean.title
                    class: "%pim_magento_connector.step.prune.class%"
                    services:
                        cleaner: pim_magento_connector.cleaner.configurable
        magento_category_export:
            title: pim_magento_connector.jobs.category_export.title
            type:  export
            steps:
                export_categories:
                    title:     pim_magento_connector.jobs.category_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.orm.category
                        processor: pim_magento_connector.processor.category
                        writer:    pim_magento_connector.writer.category
                    parameters:
                        batch_size: 1
                prune_categories:
                    title: pim_import_export.jobs.category_clean.clean.title
                    class: "%pim_magento_connector.step.prune.class%"
                    services:
                        cleaner: pim_magento_connector.cleaner.category

        magento_attribute_export:
            title: pim_magento_connector.jobs.attribute_export.title
            type:  export
            steps:
                export_attributes:
                    title:     pim_magento_connector.jobs.attribute_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.orm.attribute
                        processor: pim_magento_connector.processor.attribute
                        writer:    pim_magento_connector.writer.attribute
                prune_attributes:
                    title: pim_import_export.jobs.attribute_clean.clean.title
                    class: "%pim_magento_connector.step.prune.class%"
                    services:
                        cleaner: pim_magento_connector.cleaner.attribute

        magento_option_export:
            title: pim_magento_connector.jobs.option_export.title
            type:  export
            steps:
                export_options:
                    title:     pim_magento_connector.jobs.option_export.export.title
                    services:
                        reader:    pim_magento_connector.reader.orm.grouped_option
                        processor: pim_magento_connector.processor.option
                        writer:    pim_magento_connector.writer.option
                prune_options:
                    title: pim_import_export.jobs.option_clean.clean.title
                    class: "%pim_magento_connector.step.prune.class%"
                    services:
                        cleaner: pim_magento_connector.cleaner.option
