parameters:
    pim_magento_connector.cleaner.product.class: Pim\Bundle\MagentoConnectorBundle\Cleaner\ProductCleaner
    pim_magento_connector.cleaner.configurable.class: Pim\Bundle\MagentoConnectorBundle\Cleaner\ConfigurableCleaner

services:
    pim_magento_connector.cleaner.product:
        class: %pim_magento_connector.cleaner.product.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_catalog.manager.product'
    pim_magento_connector.cleaner.configurable:
        class: %pim_magento_connector.cleaner.configurable.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_catalog.manager.product'
            - '@pim_magento_connector.manager.group'
