parameters:
    pim_magento_connector.processor.product.class: Pim\Bundle\MagentoConnectorBundle\Processor\ProductMagentoProcessor
    pim_magento_connector.writer.product.class:    Pim\Bundle\MagentoConnectorBundle\Writer\ProductMagentoWriter

services:

    # processors
    pim_magento_connector.processor.product:
        class: %pim_magento_connector.processor.product.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.guesser.magento_normalizer'
            - '@pim_import_export.converter.metric'

    # writers
    pim_magento_connector.writer.product:
        class: %pim_magento_connector.writer.product.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.guesser.magento_webservice'
