parameters:
    pim_magento_connector.processor.product.class: Pim\Bundle\MagentoConnectorBundle\Processor\ProductMagentoProcessor
    pim_magento_connector.writer.product.class:    Pim\Bundle\MagentoConnectorBundle\Writer\ProductMagentoWriter

services:

    # processors
    pim_magento_connector.processor.product:
        class: %pim_magento_connector.processor.product.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.webservice.magento_soap'
            - '@pim_magento_connector.normalizer.product_create'
            - '@pim_magento_connector.normalizer.product_update'
            - '@pim_import_export.converter.metric'

    # writers
    pim_magento_connector.writer.product:
        class: %pim_magento_connector.writer.product.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.webservice.magento_soap'