parameters:
    pim_magento_connector.entity.category_mapping.class: Pim\Bundle\MagentoConnectorBundle\Entity\MagentoCategoryMapping
    pim_magento_connector.entity.simple_mapping.class: Pim\Bundle\MagentoConnectorBundle\Entity\SimpleMapping
