connector:
    name: Magento Connector
    jobs:
       product_export:
           title: pim_magento_connector.jobs.product_export.title
           type:  export
           steps:
               export:
                   title:     pim_magento_connector.jobs.product_export.export.title
                   reader:    pim_magento_connector.reader.product
                   processor: pim_magento_connector.processor.product
                   writer:    pim_magento_connector.writer.product