parameters:
    pim_magento_connector.manager.group.class: Pim\Bundle\MagentoConnectorBundle\Manager\GroupManager
    pim_magento_connector.manager.category_mapping.class: Pim\Bundle\MagentoConnectorBundle\Manager\CategoryMappingManager

services:
    # manager
    pim_magento_connector.manager.group:
        class: %pim_magento_connector.manager.group.class%
        arguments:
            - '@doctrine'
            - %pim_catalog.entity.product.class%
            - %pim_catalog.entity.attribute.class%
            - %pim_catalog.entity.group.class%

    pim_magento_connector.manager.category_mapping:
        class: %pim_magento_connector.manager.category_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.category_mapping.class%

