parameters:
    pim_magento_connector.manager.group.class: Pim\Bundle\MagentoConnectorBundle\Manager\GroupManager
    pim_magento_connector.manager.magento.group.class: Pim\Bundle\MagentoConnectorBundle\Manager\MagentoGroupManager
    pim_magento_connector.manager.locale.class: Pim\Bundle\MagentoConnectorBundle\Manager\LocaleManager
    pim_magento_connector.manager.currency.class: Pim\Bundle\MagentoConnectorBundle\Manager\CurrencyManager
    pim_magento_connector.manager.category_mapping.class: Pim\Bundle\MagentoConnectorBundle\Manager\CategoryMappingManager
    pim_magento_connector.manager.family_mapping.class: Pim\Bundle\MagentoConnectorBundle\Manager\FamilyMappingManager
    pim_magento_connector.manager.group_mapping.class: Pim\Bundle\MagentoConnectorBundle\Manager\AttributeGroupMappingManager
    pim_magento_connector.manager.attribute_mapping.class: Pim\Bundle\MagentoConnectorBundle\Manager\AttributeMappingManager
    pim_magento_connector.manager.simple_mapping.class: Pim\Bundle\ConnectorMappingBundle\Manager\SimpleMappingManager
    pim_magento_connector.manager.association_type.class: Pim\Bundle\MagentoConnectorBundle\Manager\AssociationTypeManager
    pim_magento_connector.manager.product_value.class: Pim\Bundle\MagentoConnectorBundle\Manager\ProductValueManager
    pim_magento_connector.manager.attribute.class: Pim\Bundle\MagentoConnectorBundle\Manager\AttributeManager

services:
    # manager
    pim_magento_connector.manager.group:
        class: %pim_magento_connector.manager.group.class%
        arguments:
            - '@doctrine'
            - %pim_catalog.entity.product.class%
            - %pim_catalog.entity.attribute.class%
            - '@pim_catalog.repository.group'

    pim_magento_connector.manager.magento.group:
        class: %pim_magento_connector.manager.magento.group.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.magento.group.class%

    pim_magento_connector.manager.category_mapping:
        class: %pim_magento_connector.manager.category_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.category_mapping.class%

    pim_magento_connector.manager.family_mapping:
        class: %pim_magento_connector.manager.family_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.family_mapping.class%

    pim_magento_connector.manager.group_mapping:
        class: %pim_magento_connector.manager.group_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.group_mapping.class%

    pim_magento_connector.manager.attribute_mapping:
        class: %pim_magento_connector.manager.attribute_mapping.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_magento_connector.entity.attribute_mapping.class%

    pim_magento_connector.manager.association_type:
        class: %pim_magento_connector.manager.association_type.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %pim_catalog.entity.association_type.class%

    pim_magento_connector.manager.product_value:
        class: %pim_magento_connector.manager.product_value.class%
        arguments:
            - %pim_catalog.entity.product_value.class%


    pim_magento_connector.manager.locale:
        class: %pim_magento_connector.manager.locale.class%
        arguments:
            - '@pim_catalog.repository.locale'
    pim_magento_connector.manager.currency:
        class: %pim_magento_connector.manager.currency.class%
        arguments:
            - '@pim_catalog.repository.currency'
            - '@pim_magento_connector.repository.currency'

    pim_magento_connector.manager.attribute:
        class: %pim_magento_connector.manager.attribute.class%
        arguments:
            - %pim_catalog.entity.attribute.class%
            - %pim_catalog.entity.attribute_option.class%
            - %pim_catalog.entity.attribute_option_value.class%
            - %pim_catalog.entity.product.class%
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.factory.attribute_type'
            - '@pim_catalog.manager.locale'
            - '@pim_catalog.factory.attribute_type'
