parameters:
    pim_magento_connector.normalizer.value.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ValueNormalizer

services:

    # normalizers
    pim_magento_connector.normalizer.value:
        class: %pim_magento_connector.normalizer.value.class%
