parameters:
    pim_magento_connector.normalizer.product.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductNormalizer

services:

    # normalizers
    pim_magento_connector.normalizer.product:
        class: %pim_magento_connector.normalizer.product.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.media'
