parameters:
    pim_magento_connector.normalizer.product_create.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductCreateNormalizer
    pim_magento_connector.normalizer.product_update.class: Pim\Bundle\MagentoConnectorBundle\Normalizer\ProductUpdateNormalizer

services:

    # normalizers
    pim_magento_connector.normalizer.product_create:
        class: %pim_magento_connector.normalizer.product_create.class%
        arguments:
            - '@pim_catalog.manager.channel'
    pim_magento_connector.normalizer.product_update:
        class: %pim_magento_connector.normalizer.product_update.class%
        arguments:
            - '@pim_catalog.manager.channel'