parameters:
    pim_magento_connector.reader.orm.bulk_entity.class: Pim\Bundle\MagentoConnectorBundle\Reader\ORM\BulkEntityReader
    pim_magento_connector.reader.orm.category.class: Pim\Bundle\MagentoConnectorBundle\Reader\ORM\CategoryReader
    pim_magento_connector.reader.orm.grouped_option.class: Pim\Bundle\MagentoConnectorBundle\Reader\ORM\GroupedOptionReader
    pim_magento_connector.reader.orm.attribute.class: Pim\Bundle\MagentoConnectorBundle\Reader\ORM\AttributeReader

services:
    # readers
    pim_magento_connector.reader.orm.bulk_simple_product:
        parent: pim_import_export.reader.orm.product
        class: %pim_import_export.reader.orm.bulk_product.class%
    pim_magento_connector.reader.orm.bulk_configurable_product:
        parent: pim_import_export.reader.orm.product
        class: %pim_import_export.reader.orm.bulk_product.class%
    pim_magento_connector.reader.orm.bulk_product_association:
        parent: pim_import_export.reader.orm.product
        class: %pim_import_export.reader.orm.bulk_product.class%

    pim_magento_connector.reader.orm.category:
        class: %pim_magento_connector.reader.orm.category.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.category.class%
            - '@pim_magento_connector.repository.category'

    pim_magento_connector.reader.orm.grouped_option:
        class: %pim_magento_connector.reader.orm.grouped_option.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.attribute_option.class%
    pim_magento_connector.reader.orm.attribute:
        class: %pim_magento_connector.reader.orm.attribute.class%
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - %pim_catalog.entity.attribute.class%

