parameters:
    pim_magento_connector.guesser.magento_webservice.class: Pim\Bundle\MagentoConnectorBundle\Guesser\MagentoWebserviceGuesser
    pim_magento_connector.guesser.magento_normalizer.class: Pim\Bundle\MagentoConnectorBundle\Guesser\MagentoNormalizerGuesser
    pim_magento_connector.validator.has_valid_credentials.class: Pim\Bundle\MagentoConnectorBundle\Validator\Constraints\HasValidCredentialsValidator
    pim_magento_connector.validator.is_valid_wsdl_url.class: Pim\Bundle\MagentoConnectorBundle\Validator\Constraints\IsValidWsdlUrlValidator
    pim_magento_connector.repository.group.class: Pim\Bundle\MagentoConnectorBundle\Validator\Constraints\IsValidWsdlUrlValidator

services:
    # guesser
    pim_magento_connector.guesser.magento_webservice:
        class: %pim_magento_connector.guesser.magento_webservice.class%
    pim_magento_connector.guesser.magento_normalizer:
        class: %pim_magento_connector.guesser.magento_normalizer.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.media'

    # validator
    pim_magento_connector.validator.has_valid_credentials:
        class: %pim_magento_connector.validator.has_valid_credentials.class%
        arguments:
            - "@pim_magento_connector.guesser.magento_webservice"
            - "@pim_magento_connector.validator.is_valid_wsdl_url"
        tags:
            - { name: validator.constraint_validator, alias: has_valid_magento_credentials }
    pim_magento_connector.validator.is_valid_wsdl_url:
        class: %pim_magento_connector.validator.is_valid_wsdl_url.class%
        tags:
            - { name: validator.constraint_validator, alias: is_valid_wsdl_url }

