parameters:
    pim_magento_connector.guesser.magento_webservice.class: Pim\Bundle\MagentoConnectorBundle\Guesser\WebserviceGuesser
    pim_magento_connector.guesser.magento_normalizer.class: Pim\Bundle\MagentoConnectorBundle\Guesser\NormalizerGuesser
    pim_magento_connector.validator.has_valid_credentials.class: Pim\Bundle\MagentoConnectorBundle\Validator\Constraints\HasValidCredentialsValidator
    pim_magento_connector.validator.magento_url.class: Pim\Bundle\MagentoConnectorBundle\Validator\Constraints\MagentoUrlValidator
    pim_magento_connector.repository.group.class: Pim\Bundle\MagentoConnectorBundle\Entity\Repository\GroupRepository
    pim_magento_connector.manager.group.class: Pim\Bundle\MagentoConnectorBundle\Manager\GroupManager
    pim_magento_connector.cleaner.product.class: Pim\Bundle\MagentoConnectorBundle\Cleaner\ProductCleaner
    pim_magento_connector.step.prune.class: Pim\Bundle\MagentoConnectorBundle\Step\PruneStep

services:
    # guesser
    pim_magento_connector.guesser.magento_webservice:
        class: %pim_magento_connector.guesser.magento_webservice.class%
    pim_magento_connector.guesser.magento_normalizer:
        class: %pim_magento_connector.guesser.magento_normalizer.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.media'
            - '@pim_magento_connector.normalizer.value'
            - '@pim_magento_connector.manager.category_mapping'
            - '@pim_magento_connector.manager.association_type'

    # validator
    pim_magento_connector.validator.has_valid_credentials:
        class: %pim_magento_connector.validator.has_valid_credentials.class%
        arguments:
            - "@pim_magento_connector.guesser.magento_webservice"
            - "@pim_magento_connector.validator.magento_url"
        tags:
            - { name: validator.constraint_validator, alias: has_valid_magento_credentials }
    pim_magento_connector.validator.magento_url:
        class: %pim_magento_connector.validator.magento_url.class%
        tags:
            - { name: validator.constraint_validator, alias: magento_url }

    pim_magento_connector.repository.category:
        class: 'Pim\Bundle\MagentoConnectorBundle\Entity\Repository\CategoryRepository'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_magento_connector.metadata.category'

    pim_magento_connector.metadata.category:
        public: false
        class: Doctrine\ORM\Mapping\ClassMetaData
        arguments:
            name: %pim_catalog.entity.category.class%

    pim_magento_connector.cleaner.product:
        class: %pim_magento_connector.cleaner.product.class%
        arguments:
            - '@pim_catalog.manager.channel'
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_catalog.manager.product'

