parameters:
    pim_magento_connector.guesser.magento_webservice.class: Pim\Bundle\MagentoConnectorBundle\Guesser\WebserviceGuesser
    pim_magento_connector.guesser.magento_normalizer.class: Pim\Bundle\MagentoConnectorBundle\Guesser\NormalizerGuesser
    pim_magento_connector.validator.has_valid_credentials.class: Pim\Bundle\MagentoConnectorBundle\Validator\Constraints\HasValidCredentialsValidator
    pim_magento_connector.validator.has_valid_currency.class: Pim\Bundle\MagentoConnectorBundle\Validator\Constraints\HasValidCurrencyValidator
    pim_magento_connector.validator.has_valid_default_locale.class: Pim\Bundle\MagentoConnectorBundle\Validator\Constraints\HasValidDefaultLocaleValidator
    pim_magento_connector.checker.url.class: Pim\Bundle\MagentoConnectorBundle\Validator\Checks\UrlChecker
    pim_magento_connector.checker.xml.class: Pim\Bundle\MagentoConnectorBundle\Validator\Checks\XmlChecker
    pim_magento_connector.checker.soap.class: Pim\Bundle\MagentoConnectorBundle\Validator\Checks\SoapChecker
    pim_magento_connector.repository.group.class: Pim\Bundle\MagentoConnectorBundle\Entity\Repository\GroupRepository
    pim_magento_connector.manager.group.class: Pim\Bundle\MagentoConnectorBundle\Manager\GroupManager
    pim_magento_connector.step.prune.class: Pim\Bundle\MagentoConnectorBundle\Step\PruneStep
    pim_magento_connector.factory.magento_soap_client.class: Pim\Bundle\MagentoConnectorBundle\Webservice\MagentoSoapClientFactory
    pim_magento_connector.repository.currency.class: Pim\Bundle\MagentoConnectorBundle\Entity\Repository\CurrencyRepository
    pim_magento_connector.repository.category.class: Pim\Bundle\MagentoConnectorBundle\Entity\Repository\CategoryRepository
    pim_magento_connector.twig.configuration_extension.class: Pim\Bundle\MagentoConnectorBundle\Twig\ConfigurationExtension

services:
    # guesser
    pim_magento_connector.guesser.magento_webservice:
        class: %pim_magento_connector.guesser.magento_webservice.class%
        arguments:
            - '@pim_magento_connector.factory.magento_soap_client'
    pim_magento_connector.guesser.magento_normalizer:
        class: %pim_magento_connector.guesser.magento_normalizer.class%
        arguments:
            - '@pim_magento_connector.factory.magento_soap_client'
            - '@pim_catalog.manager.channel'
            - '@pim_catalog.manager.media'
            - '@pim_magento_connector.normalizer.value'
            - '@pim_magento_connector.manager.category_mapping'
            - '@pim_magento_connector.manager.association_type'
            - '@pim_magento_connector.manager.product_value'

    # validator
    pim_magento_connector.validator.has_valid_credentials:
        class: %pim_magento_connector.validator.has_valid_credentials.class%
        arguments:
            - '@pim_magento_connector.guesser.magento_webservice'
            - '@pim_magento_connector.checker.url'
            - '@pim_magento_connector.checker.soap'
            - '@pim_magento_connector.checker.xml'
        tags:
            - { name: validator.constraint_validator, alias: has_valid_magento_credentials }
    pim_magento_connector.validator.has_valid_currency:
        class: %pim_magento_connector.validator.has_valid_currency.class%
        arguments:
            - '@pim_catalog.manager.channel'
        tags:
            - { name: validator.constraint_validator, alias: has_valid_currency }
    pim_magento_connector.validator.has_valid_default_locale:
        class: %pim_magento_connector.validator.has_valid_default_locale.class%
        arguments:
            - '@pim_catalog.manager.channel'
        tags:
            - { name: validator.constraint_validator, alias: has_valid_default_locale }

    # Checker
    pim_magento_connector.checker.url:
        class: %pim_magento_connector.checker.url.class%
    pim_magento_connector.checker.xml:
        class: %pim_magento_connector.checker.xml.class%
    pim_magento_connector.checker.soap:
        class: %pim_magento_connector.checker.soap.class%

    pim_magento_connector.repository.category:
        class: %pim_magento_connector.repository.category.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_magento_connector.metadata.category'
    pim_magento_connector.repository.currency:
        class: %pim_magento_connector.repository.currency.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_magento_connector.metadata.currency'

    pim_magento_connector.metadata.category:
        public: false
        class: Doctrine\ORM\Mapping\ClassMetaData
        arguments:
            name: %pim_catalog.entity.category.class%
    pim_magento_connector.metadata.currency:
        public: false
        class: Doctrine\ORM\Mapping\ClassMetaData
        arguments:
            name: %pim_catalog.entity.currency.class%


    pim_magento_connector.factory.magento_soap_client:
        class: %pim_magento_connector.factory.magento_soap_client.class%

    pim_magento_connector.twig.configuration_extension:
        class: '%pim_magento_connector.twig.configuration_extension.class%'
        arguments:
            name: @file_locator
        tags:
            - { name: twig.extension }
