language: php
php:
  - "5.5"
  - "5.4"
  - "hhvm"

cache:
  directories:
      - vendor

before_script:
  - composer self-update
  - composer install

script: bin/phpspec run -fpretty

matrix:
  allow_failures:
      - php: hhvm
