families:
    shirt:
        labels:
            en_US: Shirt
            fr_FR: Chemise
        attributes:
            - sku
            - name
            - short_description
            - description
            - size
            - color
            - price
            - weight
            - visibility
        attributeAsLabel: name
        requirements:
            magento:
                - name
                - short_description
                - description
                - size
                - color
                - price
                - weight
                - visibility