families:
    Default:
        labels:
            en_US: Shirt
            fr_FR: Chemise
        attributes:
            - sku
            - name
            - short_description
            - description
            - price
            - weight
        attributeAsLabel: name
        requirements:
            magento:
                - name
                - short_description
                - description
                - price
                - weight