groups:
    akeneo_tshirt:
        type: VARIANT
        labels:
            en_US: Akeneo T-Shirt
            fr_FR: T-Shirt Akeneo
        attributes:
            - size
    oro_tshirt:
        type: VARIANT
        labels:
            en_US: Oro T-Shirt
            fr_FR: T-Shirt Oro
        attributes:
            - size
